# Generated by Django 5.2.8 on 2025-12-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('tipo_usuario', models.CharField(max_length=50, verbose_name='Tipo de Usuario')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
