# Generated by Django 5.2.8 on 2025-12-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_options_usuario_apellidos_usuario_dni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
