# Generated by Django 5.2.8 on 2025-12-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(verbose_name='Puntuación')),
                ('comentario', models.TextField(null=True, verbose_name='Comentario')),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Valoración')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.empresa', verbose_name='Empresa')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.trabajador', verbose_name='Trabajador')),
            ],
        ),
    ]
