# Generated by Django 5.2.8 on 2025-12-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_administrador_alter_empresa_options_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracion',
            options={'ordering': ['-fecha_valoracion'], 'verbose_name': 'Valoración', 'verbose_name_plural': 'Valoraciones'},
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_realizadas', to='profiles.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to='profiles.trabajador', verbose_name='Trabajador'),
        ),
    ]
