# Generated by Django 5.2.8 on 2025-12-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0002_alter_usuario_options_usuario_apellidos_usuario_dni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id_referencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID de Referencia'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='users.usuario', verbose_name='Usuario'),
        ),
    ]
