# Generated by Django 5.2.8 on 2025-12-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.usuario')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('cif', models.CharField(max_length=20, unique=True, verbose_name='CIF')),
                ('calle', models.CharField(max_length=300, verbose_name='Calle')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('localidd', models.CharField(max_length=200, verbose_name='Localidad')),
                ('codigo_postal', models.CharField(max_length=100, verbose_name='Código Postal')),
                ('tipo_establecimiento', models.CharField(max_length=50, verbose_name='Tipo Establecimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('valoracion_media', models.FloatField(default=0.0, verbose_name='Valoración Media')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('calle', models.CharField(max_length=300, verbose_name='Calle')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(max_length=100, verbose_name='Código Postal')),
                ('experiencia_laboral', models.TextField(verbose_name='Experiencia Laboral')),
                ('disponibilidad_horaria', models.TextField(verbose_name='Disponibilidad Horaria')),
                ('valoracion_media', models.FloatField(default=0.0, verbose_name='Valoración Media')),
                ('bloqueado', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.TextField(blank=True, null=True, verbose_name='Motivo de Bloqueo')),
                ('fecha_fin_bloqueo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin de Bloqueo')),
                ('cancelaciones_totales', models.IntegerField(default=0, verbose_name='Cancelaciones Totales')),
            ],
        ),
    ]
