# Generated by Django 5.2.8 on 2025-12-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('users', '0002_alter_usuario_options_usuario_apellidos_usuario_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrador', serialize=False, to='users.usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='localidd',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empresa',
            name='localidad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='empresa', serialize=False, to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_establecimiento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo Establecimiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='disponibilidad_horaria',
            field=models.TextField(blank=True, verbose_name='Disponibilidad Horaria'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='experiencia_laboral',
            field=models.TextField(blank=True, verbose_name='Experiencia Laboral'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trabajador', serialize=False, to='users.usuario'),
        ),
    ]
