# Generated by Django 5.2.8 on 2025-12-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_administrador_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'ordering': ['id_usuario'], 'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre_empresa'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['id_usuario__nombre'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_establecimiento',
            field=models.CharField(choices=[], max_length=50, verbose_name='Tipo Establecimiento'),
        ),
    ]
