# Generated by Django 5.2.8 on 2025-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_administrador_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo_establecimiento',
            field=models.CharField(choices=[("<enum 'TipoEstablecimiento'>", 'Tipoestablecimiento')], max_length=50, verbose_name='Tipo Establecimiento'),
        ),
    ]
