# Generated by Django 5.2.8 on 2026-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_empresa_tipo_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo_establecimiento',
            field=models.CharField(choices=[("<enum 'TipoEstablecimiento'>", 'Tipoestablecimiento')], max_length=50, verbose_name='Tipo Establecimiento'),
        ),
    ]
