# Generated by Django 5.2.8 on 2025-12-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, null=True, verbose_name='Titulo')),
                ('descripcion', models.TextField()),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Precio por Hora €')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total €')),
                ('tipo_contrato', models.CharField(max_length=100, null=True, verbose_name='Tipo de Contrato')),
                ('jornada', models.CharField(max_length=100, null=True, verbose_name='Jornada')),
                ('plazas_totales', models.IntegerField(null=True, verbose_name='Plazas Totales')),
                ('plazas_disponibles', models.IntegerField(null=True, verbose_name='Plazas Disponibles')),
                ('horario', models.CharField(max_length=200, null=True, verbose_name='Horario')),
                ('urgente', models.BooleanField(default=False)),
                ('fecha_evento', models.DateField(null=True, verbose_name='Fecha del Evento')),
                ('estado', models.CharField(max_length=50, null=True, verbose_name='Estado')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('fecha_cierre', models.DateTimeField(null=True, verbose_name='Fecha de Cierre')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.categoria', verbose_name='Categoría')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.trabajador', verbose_name='Trabajador')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.oferta', verbose_name='Oferta')),
            ],
        ),
    ]
