# Generated by Django 5.2.8 on 2025-12-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0002_administrador_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='jobs.oferta', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='profiles.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='jobs.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='profiles.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Precio por Hora €'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='titulo',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total €'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('oferta', 'trabajador')},
        ),
    ]
