# Generated by Django 5.2.8 on 2025-12-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_categoria_options_alter_inscripcion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('En Proceso', 'En Proceso')], default='Abierta', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='horario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='jornada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='plazas_disponibles',
            field=models.IntegerField(default=0, null=True, verbose_name='Plazas Disponibles'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='plazas_totales',
            field=models.IntegerField(default=0, null=True, verbose_name='Plazas Totales'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio por Hora €'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total €'),
        ),
    ]
