# Generated by Django 5.2.8 on 2025-12-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGrupal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=200, verbose_name='Nombre del Grupo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha desactivación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('oferta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.oferta', verbose_name='Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeGrupal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha envío')),
                ('chat_grupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='messaging.chatgrupal', verbose_name='Chat Grupal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MensajePrivado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Envío')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='users.usuario', verbose_name='Emisor')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='users.usuario', verbose_name='Receptor')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
                ('fecha_union', models.DateTimeField(auto_now_add=True, verbose_name='Fecha unión')),
                ('chat_grupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='messaging.chatgrupal', verbose_name='Chat grupal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
