# Generated by Django 5.2.8 on 2025-12-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_categoria_options_alter_inscripcion_options_and_more'),
        ('messaging', '0001_initial'),
        ('users', '0002_alter_usuario_options_usuario_apellidos_usuario_dni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgrupal',
            options={'verbose_name': 'Chat Grupal', 'verbose_name_plural': 'Chats Grupales'},
        ),
        migrations.AlterModelOptions(
            name='mensajegrupal',
            options={'ordering': ['fecha_envio'], 'verbose_name': 'Mensaje Grupal', 'verbose_name_plural': 'Mensajes Grupales'},
        ),
        migrations.AlterModelOptions(
            name='mensajeprivado',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Mensaje Privado', 'verbose_name_plural': 'Mensajes Privados'},
        ),
        migrations.AlterModelOptions(
            name='participantechat',
            options={'verbose_name': 'Participante de Chat', 'verbose_name_plural': 'Participantes de Chat'},
        ),
        migrations.AlterField(
            model_name='chatgrupal',
            name='oferta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_grupal', to='jobs.oferta', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='mensajegrupal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_grupales', to='users.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='participantechat',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_chat', to='users.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='participantechat',
            unique_together={('chat_grupal', 'usuario')},
        ),
    ]
