# Generated by Django 5.2.8 on 2025-12-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_chatgrupal_options_alter_mensajegrupal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgrupal',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Chat Grupal', 'verbose_name_plural': 'Chats Grupales'},
        ),
        migrations.AlterModelOptions(
            name='participantechat',
            options={'ordering': ['-fecha_union'], 'verbose_name': 'Participante de Chat', 'verbose_name_plural': 'Participantes de Chat'},
        ),
    ]
